###################################################
#
# Makefile
# Author: Methodios Zacharioudakis
#
###################################################

all: simulator

simulator: main.c Movie.c Movie.h
	gcc -ansi -g -o simulator main.c Movie.c

clean:
	rm -f simulator
	clear